schema_version: 1

context:
  version: "0.3.0"
  python_min: "3.12"

package:
  name: globato
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/g/globato/globato-${{ version }}.tar.gz
  sha256: cec89691e2b41ea1e69bd785eaccafa7292b4ef3234722347f95cf692afad6e4

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - globato = globato.cli:cli
      - wafflez = globato.cli.wafflez:wafflez_build

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling >=1.5.0
    - hatch-vcs
    - pip
  run:
    - python >=${{ python_min }}
    - fetchez >=0.6.4
    - transformez >=0.4.2
    - click
    - fiona
    - h5py
    - laspy
    # laszip is an optional dependency of laspy, expressed as laspy[lazrs,laszip] upstream
    - laszip
    - matplotlib-base
    - numpy >1.24
    - pandas
    - pyproj >3.6.1
    - pyshp
    - pyyaml
    - rasterio >1.4.0
    - requests
    - scipy
    - shapely

tests:
  - python:
      python_version:
        - ${{ python_min }}.*
        - "*"
      pip_check: true
      imports:
        - globato
  - script:
      - globato --help
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  homepage: https://github.com/continuous-dems/globato
  summary: |
    A suite of specialized data processors (Multibeam, Lidar, Raster), etc. for
    the Fetchez ecosystem.
  license: MIT
  license_file: LICENSE
  repository: https://github.com/continuous-dems/globato
  documentation: https://globato.readthedocs.io/

extra:
  recipe-maintainers:
    - matth-love
    - mfisher87
