schema_version: 1

context:
  version: "0.3.9"
  python_min: "3.12"

package:
  name: globato
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/g/globato/globato-${{ version }}.tar.gz
  sha256: ac7cf6fb1e9008decd75a41aac81905926da4a314781db95291633f65fea857c

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  python:
    entry_points:
      - globato = globato.cli:cli
      - wafflez = globato.cli.wafflez:wafflez_build

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling >=1.5.0
    - hatch-vcs
    - pip
  run:
    - python >=${{ python_min }}
    - fetchez >=0.9.0
    - transformez >=1.0.0
    - click
    - h5py
    - laspy
    # laszip is an optional dependency of laspy, expressed as laspy[lazrs,laszip] upstream
    - laszip
    - matplotlib-base
    - numpy >1.24
    - pandas
    - geopandas >=1.0.0
    - pyproj >3.6.1
    - pyshp
    - pyyaml
    - rasterio >1.4.0
    - requests
    - scipy
    - shapely >=2.0.0
    - pyogrio >=0.7.0
    - libgdal-netcdf
    - libgdal-hdf5
    - gmt
    - pygmt

tests:
  - python:
      python_version:
        - ${{ python_min }}.*
        - "*"
      pip_check: true
      imports:
        - globato
  - script:
      - globato --help
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  homepage: https://github.com/continuous-dems/globato
  summary: |
    A suite of specialized data processors (Multibeam, Lidar, Raster), etc. for
    the Fetchez ecosystem.
  license: MIT
  license_file: LICENSE
  repository: https://github.com/continuous-dems/globato
  documentation: https://globato.readthedocs.io/

extra:
  recipe-maintainers:
    - matth-love
    - mfisher87
